#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

entry("trace"); # ADD entry("trace") in usys.pl
# 在usys.S里面生成:
# .global trace
# trace:              #用户态跳板函数
#  li a7, SYS_trace   #系统调用id存入a7寄存器
#  ecall              #系统调用：跳到内核态统一系统调用处理函数syscall()
#  ret
entry("sysinfo"); # ADD entry("sysinfo") in usys.pl
